

SELECT        HO, TEN, DIEN_THOAI
FROM            SINH_VIEN

SELECT        SINH_VIEN.MA_SV, SINH_VIEN.TEN, SINH_VIEN.DIA_CHI, VUNG.HUYEN, VUNG.TINH
FROM            SINH_VIEN INNER JOIN
                         VUNG ON SINH_VIEN.MA_SO = VUNG.MA_SO			 
SELECT        *
FROM            VUNG

SELECT        MA_SV, HO, TEN, DIA_CHI, DIEN_THOAI
FROM            SINH_VIEN

SELECT        GIAO_VIEN.HO, GIAO_VIEN.TEN, GIAO_VIEN.DIA_CHI, VUNG.HUYEN, VUNG.TINH
FROM            GIAO_VIEN INNER JOIN
                         VUNG ON GIAO_VIEN.MA_SO = VUNG.MA_SO

SELECT        SINH_VIEN.MA_SV, SINH_VIEN.HO, SINH_VIEN.TEN, DANG_KY.MA_LOP
FROM            SINH_VIEN INNER JOIN
                         DANG_KY ON SINH_VIEN.MA_SV = DANG_KY.MA_SV
SELECT        SINH_VIEN.MA_SV, SINH_VIEN.HO, SINH_VIEN.TEN, LOP.MA_LOP, LOP.TEN_LOP
FROM            LOP CROSS JOIN
                         SINH_VIEN